# Generated by Django 3.0.3 on 2020-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
