# Generated by Django 3.0.3 on 2020-07-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
