# Generated by Django 3.0.3 on 2020-07-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200730_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='base/media/logo.jpg', null=True, upload_to=''),
        ),
    ]
