# Generated by Django 3.0.8 on 2020-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200802_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='placeholder', max_length=60, null=True),
        ),
    ]
